# Generated by Django 5.1 on 2024-12-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("connect", "Connect"),
                            ("understand", "Understand"),
                            ("act", "Act"),
                        ],
                        max_length=10,
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                ("total_completions", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
