# Generated by Django 5.1 on 2024-12-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_ID", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("bio", models.CharField(max_length=300)),
                ("total_points", models.IntegerField(default=0)),
                ("birthdate", models.DateField(null=True)),
                ("email", models.EmailField(max_length=320, unique=True)),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[
                            (2, "Public"),
                            (1, "Friends Only"),
                            (0, "BlueCrew Only"),
                        ],
                        default=0,
                    ),
                ),
                ("avatar", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
