# Generated by Django 5.1 on 2024-12-12 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=30, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                ("bio", models.CharField(blank=True, max_length=300)),
                ("total_points", models.IntegerField(default=0)),
                ("birthdate", models.DateField(default=datetime.date(2000, 1, 1))),
                ("email", models.EmailField(max_length=320, unique=True)),
                (
                    "visibility",
                    models.IntegerField(
                        choices=[
                            (2, "Public"),
                            (1, "Friends Only"),
                            (0, "BlueCrew Only"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "avatar",
                    models.IntegerField(
                        choices=[
                            (0, "Avatar 0"),
                            (1, "Avatar 1"),
                            (2, "Avatar 2"),
                            (3, "Avatar 3"),
                            (4, "Avatar 4"),
                            (5, "Avatar 5"),
                        ],
                        default=0,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
