# Generated by Django 5.1 on 2024-12-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("connect", "Connect"),
                            ("understand", "Understand"),
                            ("act", "Act"),
                        ],
                        max_length=10,
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                ("total_completions", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
