# Generated by Django 5.1 on 2024-12-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0003_friendshiptable"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendshiptable",
            unique_together={("requester", "receiver")},
        ),
    ]
