# Generated by Django 5.1 on 2024-12-14 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0004_alter_friendshiptable_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FriendshipTable",
            new_name="Friendship",
        ),
    ]
