# Generated by Django 5.1 on 2024-12-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0005_rename_friendshiptable_friendship"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                fields=("requester", "receiver"), name="unique_friendship"
            ),
        ),
    ]
