# Generated by Django 5.1.4 on 2025-01-04 00:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0006_alter_friendship_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BingoGrid",
            fields=[
                ("grid_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "challenges",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
