# Generated by Django 5.1.4 on 2025-01-08 12:28

import django.db.models.deletion
import sortedm2m.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bingo", "0006_alter_friendship_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BingoGrid",
            fields=[
                ("grid_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ChallengeInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="challenge_images/")),
                ("completed", models.BooleanField(default=False)),
                ("consent", models.BooleanField(default=False)),
                ("date_started", models.DateTimeField(auto_now_add=True)),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GridInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-total_points", "username"]},
        ),
        migrations.AddField(
            model_name="user",
            name="gender_identity",
            field=models.IntegerField(
                choices=[
                    (0, "Male"),
                    (1, "Female"),
                    (2, "Non-Binary"),
                    (3, "Other"),
                    (4, "Prefer not to say"),
                ],
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="indigenous_identity",
            field=models.BooleanField(
                choices=[(0, "Prefer not to say"), (1, "Yes"), (2, "No")], default=0
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-total_points"], name="bingo_user_total_p_f1bcb7_idx"
            ),
        ),
        migrations.AddField(
            model_name="bingogrid",
            name="challenges",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None, to="bingo.challenge"
            ),
        ),
        migrations.AddField(
            model_name="challengeinteraction",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bingo.challenge"
            ),
        ),
        migrations.AddField(
            model_name="challengeinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="gridinteraction",
            name="challenge_interactions",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True, help_text=None, to="bingo.challengeinteraction"
            ),
        ),
        migrations.AddField(
            model_name="gridinteraction",
            name="grid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bingo.bingogrid"
            ),
        ),
        migrations.AddField(
            model_name="gridinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="gridinteraction",
            constraint=models.UniqueConstraint(
                fields=("user", "grid"), name="unique_user_grid"
            ),
        ),
    ]
