# Generated by Django 5.1 on 2025-01-04 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0006_alter_friendship_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender_identity",
            field=models.IntegerField(
                choices=[
                    (0, "Male"),
                    (1, "Female"),
                    (2, "Non-Binary"),
                    (3, "Other"),
                    (4, "Prefer not to say"),
                ],
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="indigenous_identity",
            field=models.BooleanField(
                choices=[(0, "Prefer not to say"), (1, "Yes"), (2, "No")], default=0
            ),
        ),
        migrations.CreateModel(
            name="ChallengeInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="challenge_images/")),
                ("completed", models.BooleanField(default=False)),
                ("consent", models.BooleanField(default=False)),
                ("date_started", models.DateTimeField(auto_now_add=True)),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bingo.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
