# Generated by Django 5.1 on 2024-12-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0006_alter_friendship_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender_identity",
            field=models.IntegerField(
                choices=[
                    (0, "Male"),
                    (1, "Female"),
                    (2, "Non-Binary"),
                    (3, "Other"),
                    (4, "Prefer not to say"),
                ],
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="indigenous_identity",
            field=models.BooleanField(default=False),
        ),
    ]
