# Generated by Django 5.1.4 on 2025-01-08 11:26

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0007_bingogrid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bingogrid",
            name="challenges",
        ),
        migrations.AddField(
            model_name="bingogrid",
            name="challenges",
            field=sortedm2m.fields.SortedManyToManyField(
                help_text=None, to="bingo.challenge"
            ),
        ),
    ]
