# Generated by Django 5.1.4 on 2025-01-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("bingo", "0007_user_gender_identity_user_indigenous_identity_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-total_points", "username"]},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-total_points"], name="bingo_user_total_p_f1bcb7_idx"
            ),
        ),
    ]
