# Generated by Django 5.1.4 on 2025-01-08 13:16

import django.db.models.deletion
import sortedm2m.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0008_alter_user_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BingoGrid",
            fields=[
                ("grid_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "challenges",
                    sortedm2m.fields.SortedManyToManyField(
                        help_text=None, to="bingo.challenge"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GridInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "challenge_interactions",
                    sortedm2m.fields.SortedManyToManyField(
                        blank=True, help_text=None, to="bingo.challengeinteraction"
                    ),
                ),
                (
                    "grid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bingo.bingogrid",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "grid"), name="unique_user_grid"
                    )
                ],
            },
        ),
    ]
