# Generated by Django 5.1.4 on 2025-01-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0008_alter_user_options_and_more"),
        ("bingo", "0008_remove_bingogrid_challenges_bingogrid_challenges"),
    ]

    operations = []
