# Generated by Django 5.1.4 on 2025-01-10 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0009_bingogrid_gridinteraction"),
    ]

    operations = [
        migrations.CreateModel(
            name="TileInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("image", models.ImageField(blank=True, upload_to="challenge_images/")),
                ("completed", models.BooleanField(default=False)),
                ("consent", models.BooleanField(default=False)),
                ("date_started", models.DateTimeField(auto_now_add=True)),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
                (
                    "grid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bingo.bingogrid",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("position__lte", 15)),
                        name="position_lte_15",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "grid", "position"),
                        name="unique_user_grid_challenege",
                    ),
                ],
            },
        ),
    ]
