# Generated by Django 5.1.4 on 2025-01-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0009_bingogrid_gridinteraction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengeinteraction",
            name="completed",
            field=models.IntegerField(
                choices=[(2, "Not Started"), (1, "Started"), (0, "Completed")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="challengeinteraction",
            name="date_started",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
