# Generated by Django 5.1.4 on 2025-01-09 03:35

import django.db.models.deletion
import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0009_bingogrid_gridinteraction"),
    ]

    operations = [
        migrations.CreateModel(
            name="NullableChallengeInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "optional_challenge_interaction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bingo.challengeinteraction",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="gridinteraction",
            name="challenge_interactions",
            field=sortedm2m.fields.SortedManyToManyField(
                blank=True, help_text=None, to="bingo.nullablechallengeinteraction"
            ),
        ),
    ]
