# Generated by Django 5.1.4 on 2025-01-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0011_move_data_to_tileinteraction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gridinteraction",
            name="challenge_interactions",
        ),
        migrations.RemoveField(
            model_name="gridinteraction",
            name="grid",
        ),
        migrations.RemoveField(
            model_name="gridinteraction",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChallengeInteraction",
        ),
        migrations.DeleteModel(
            name="GridInteraction",
        ),
    ]
