# Generated by Django 5.1.4 on 2025-01-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0012_remove_gridinteraction_challenge_interactions_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tileinteraction",
            name="unique_user_grid_challenege",
        ),
        migrations.AddConstraint(
            model_name="tileinteraction",
            constraint=models.UniqueConstraint(
                fields=("user", "grid", "position"), name="unique_user_grid_challenge"
            ),
        ),
    ]
