# Generated by Django 5.1.5 on 2025-02-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0013_remove_tileinteraction_unique_user_grid_challenege_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="indigenous_identity",
            field=models.IntegerField(
                choices=[(0, "Prefer not to say"), (1, "Yes"), (2, "No")], default=0
            ),
        ),
    ]
