# Generated by Django 5.1.5 on 2025-02-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0013_remove_tileinteraction_unique_user_grid_challenege_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tileinteraction",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
