# Generated by Django 5.1.5 on 2025-02-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0014_alter_user_indigenous_identity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tileinteraction",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
