# Generated by Django 5.1.5 on 2025-02-06 04:20

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0015_alter_tileinteraction_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tileinteraction",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=False,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                upload_to="",
            ),
        ),
    ]
