# Generated by Django 5.1.5 on 2025-02-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0016_alter_tileinteraction_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="visibility",
            field=models.IntegerField(
                choices=[(2, "Public"), (1, "Friends Only"), (0, "Staff Only")],
                default=0,
            ),
        ),
    ]
