# Generated by Django 5.1.5 on 2025-02-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0018_tileinteraction_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
