# Generated by Django 5.1.6 on 2025-02-22 13:09

import bingo.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0018_tileinteraction_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tileinteraction",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=False,
                quality=-1,
                scale=None,
                size=[1920, 1080],
                upload_to="",
                validators=[bingo.models.file_size],
            ),
        ),
    ]
