# Generated by Django 5.1.6 on 2025-02-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bingo", "0020_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="visibility",
            field=models.IntegerField(
                choices=[(2, "Public"), (1, "Friends Only"), (0, "Staff Only")],
                default=1,
            ),
        ),
    ]
